// Code generated by goagen v1.5.13, DO NOT EDIT.
//
// API "adder": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/kod-source/GoaLessonVersion1/design
// --out=/Users/horikoudai/Documents/ProgrammingLearning/GoaLessonVersion1
// --version=v1.5.13

package app
